# dimensions:
#   "15x15":
#     min: 95
#     max: 105
#   "20x20":
#     min: 120
#     max: 130
# length:
#   "12000":
#     min: 1000
#     max: 1100

dimensions:
  "15x15":
    min: 90
    max: 110
  "20x20":
    min: 120
    max: 140
length:
  "2000":
    min: 1000
    max: 1100